using TMPro;
using UnityEditor;
using UnityEngine;

namespace QDC.Text
{
    [ExecuteAlways]
    [AddComponentMenu("UI/Text Wrapper")]
    public class TextWrapper : MonoBehaviour
    {
        [SerializeField] private string textTest;

        [SerializeField] private TextMeshProUGUI prefab;

        [SerializeField] [HideInInspector]
        private PropertyModification[] textOverrides;

        private DrivenRectTransformTracker textTransformTracker;

        private TextMeshProUGUI textMeshPro;
        
        public TextMeshProUGUI TextMeshPro => textMeshPro;
        
        public TextMeshProUGUI Prefab
        {
            get => prefab;
            set => prefab = value;
        }

        public string Text
        {
            get => textMeshPro.text;
            set => textMeshPro.text = value;
        }

        public PropertyModification[] TextOverrides
        {
            get => textOverrides;
            set => textOverrides = value;
        }

        private void Awake()
        {
            CreateUnderlyingText();
        }

        private void OnEnable()
        {
            CreateUnderlyingText();
            textMeshPro.enabled = true;
        }

        private void OnDisable()
        {
            if (textMeshPro)
                textMeshPro.enabled = false;
        }

        [ContextMenu("Reset Underlying Text")]
        public void ResetText()
        {
            DestroyText();
            CreateUnderlyingText();
        }

        private void OnValidate()
        {
            if (!prefab)
            {
                if (textMeshPro)
                    DestroyText();
                return;
            }

            if (!textMeshPro)
                return;

            textMeshPro.enabled = enabled;

            if (textTest != textMeshPro.text)
            {
                textMeshPro.text = textTest;
            }
        }

        private void OnDestroy()
        {
            DestroyText();
        }

        private void CreateUnderlyingText()
        {
            // Don't have to do anything
            if (textMeshPro) return;
            if (!prefab) return;

            textMeshPro = (TextMeshProUGUI)PrefabUtility.InstantiatePrefab(prefab, transform);
            var tmpGameObject = textMeshPro.gameObject;
            tmpGameObject.hideFlags = HideFlags.DontSave;
            
            PrefabUtility.SetPropertyModifications(textMeshPro, textOverrides);

            var rectTransform = tmpGameObject.GetComponent<RectTransform>();
            rectTransform.SetAsFirstSibling();

#if UNITY_EDITOR
            Autogenerated.UnderlyingTextTag tag;
            if (!tmpGameObject.TryGetComponent(out tag))
                tag = tmpGameObject.AddComponent<Autogenerated.UnderlyingTextTag>();
            tag.wrapper = this;
#endif

            textTransformTracker.Clear();
            textTransformTracker.Add(this, rectTransform, DrivenTransformProperties.All);

            rectTransform.anchorMax = Vector2.one;
            rectTransform.anchorMin = Vector2.zero;
            rectTransform.sizeDelta = Vector2.zero;
        }

        public void DestroyText()
        {
            // Destroy text if it exists
            try
            {
#if UNITY_EDITOR
                DestroyImmediate(textMeshPro.gameObject);
#else
                Destroy(tmpText.gameObject);
#endif
            }
            catch
            {
                // ignored
            }
        }
    }
}