using System;
using System.Diagnostics;
using TMPro;
using UnityEngine;

namespace QDC.Text
{
    public static partial class Autogenerated
    {
        // Component added to underlying text for TextWrapper
        // It's used only in editor
        [ExecuteInEditMode]
        public class UnderlyingTextTag : MonoBehaviour
        {
            [NonSerialized] public TextWrapper wrapper;

            private TextMeshProUGUI tmpComponent;

            private string serializedTMP;

            void OnEnable()
            {
                tmpComponent = GetComponent<TextMeshProUGUI>();
                if (tmpComponent == null)
                    DestroyImmediate(this);
            }

            void Update()
            {
                CheckIfChanged();
            }

            [Conditional("UNITY_EDITOR")]
            private void CheckIfChanged()
            {
                if (!tmpComponent)
                {
                    DestroyImmediate(this);
                    return;
                }

                var current = JsonUtility.ToJson(tmpComponent);
                if (serializedTMP != current)
                {
                    serializedTMP = current;
                    wrapper.SetTextOverrides();
                }
            }
        }
    }
}