using UnityEditor;
using UnityEngine.UIElements;

namespace QDC.Text.Editor
{
    [CustomEditor(typeof(Autogenerated.UnderlyingTextTag), true)]
    public class UnderlyingTextTag : UnityEditor.Editor
    {
        public override VisualElement CreateInspectorGUI()
        {
            return new VisualElement();
        }

        private void OnDisable()
        {
            var tag = target as Autogenerated.UnderlyingTextTag;
            tag?.wrapper?.SetTextOverrides();
        }
    }
}